### ISSUE TITLE
Improvement Proposal: Font contrast

### ISSUE THREAD

**Issue by JSKitty** [FlorentG74/PIVX-Doc-Website-Content#34]
In certain areas, the font colour is closely matching the background colour, it is usually still readable, but nonetheless a strain on the eyes and just not quite standard design principles.

One good example is this small section of each article:
![image](https://user-images.githubusercontent.com/42538664/139094358-dd47339b-bb59-4a0a-a695-0f16d002a94b.png)

A white font would contrast well here.

**Comment by FlorentG74** [comment]
Updated theme thanks for the feedback!

**Comment by JSKitty** [comment]
Howdy @FlorentG74, are you sure this is fixed? Or has the website not updated?

The website still looks like this:
![image](https://user-images.githubusercontent.com/42538664/139727586-056ea55e-5b2e-4caf-b6a2-9ba248dbd2b7.png)

On this page, for example: https://docs.pivx.org/pivx-core-wallet

**Comment by FlorentG74** [comment]
Yeah apols I still have a dependency on Kyeno to deploy core changes on the pivot.org website (we'll be working on it). this is what it looks like on my test server: https://p558.phpnet.org/pivx_doc/pivx-core-wallet

**Comment by JSKitty** [comment]
Sweet ^ No problem in that case!
